title = "Welcome to Dev-Stories!"
description = "On Java, Spring Boot, Cloud, Microservices, Angular and Everything Dev"
baseURL = "https://dev-stories.com/"
languageCode = "en-us"
theme = "ananke"


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-109508067-2"
enableRobotsTXT = true


disqusShortname = "https-dev-stories-com"


[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
 

[params]
  NewsletterSignup = "https://tinyletter.com/dev-storiesdotcom"
  favicon = ""
  facebook = ""
  twitter = "https://twitter.com/Dev_Stories_"
  instagram = ""
  youtube = ""
  github = "https://github.com/Lockoo"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/lucas-spiller/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/binary_background.jpg"
  recent_posts_number = 2
  custom_css = ["css/custom.css"]

	
 
 
[related]
  threshold = 80
  includeNewer = true
  toLower =  true
  
  [[related.indices]]
	name = "tags"
	weight = 100.0

  [[related.indices]]
	name = "date"
	weight = 10.0