[Settings]

[build]
  publish = "public"
  command = "hugo"

[context.production]
  HUGO_VERSION = "0.53"
	
[[redirects]]
  from = "https://dev-stories.netlify.com/*"
  to = "https://dev-stories.com/:splat"